export { NH1, NH2, NH3, NH4, NH5, NH6 } from 'naive-ui/lib/typography/src/headers'
export type { HeaderProps as H1Props } from 'naive-ui/lib/typography/src/create-header'
export type { HeaderProps as H2Props } from 'naive-ui/lib/typography/src/create-header'
export type { HeaderProps as H3Props } from 'naive-ui/lib/typography/src/create-header'
export type { HeaderProps as H4Props } from 'naive-ui/lib/typography/src/create-header'
export type { HeaderProps as H5Props } from 'naive-ui/lib/typography/src/create-header'
export type { HeaderProps as H6Props } from 'naive-ui/lib/typography/src/create-header'
export { default as NA } from 'naive-ui/lib/typography/src/a'
export type { AProps } from 'naive-ui/lib/typography/src/a'
export { default as NP } from 'naive-ui/lib/typography/src/p'
export type { PProps } from 'naive-ui/lib/typography/src/p'
export { default as NBlockquote } from 'naive-ui/lib/typography/src/blockquote'
export type { BlockquoteProps } from 'naive-ui/lib/typography/src/blockquote'
export { default as NHr } from 'naive-ui/lib/typography/src/hr'
export { default as NUl } from 'naive-ui/lib/typography/src/ul'
export type { UlProps } from 'naive-ui/lib/typography/src/ul'
export { default as NOl } from 'naive-ui/lib/typography/src/ol'
export type { OlProps } from 'naive-ui/lib/typography/src/ol'
export { default as NLi } from 'naive-ui/lib/typography/src/li'
export { default as NText } from 'naive-ui/lib/typography/src/text'
export type { TextProps } from 'naive-ui/lib/typography/src/text'
