export { default as NTabs } from 'naive-ui/lib/tabs/src/Tabs'
export type { TabsProps } from 'naive-ui/lib/tabs/src/Tabs'
export { default as NTabPane } from 'naive-ui/lib/tabs/src/TabPane'
export type { TabPaneProps } from 'naive-ui/lib/tabs/src/TabPane'
export { default as NTab } from 'naive-ui/lib/tabs/src/Tab'
export type { TabProps } from 'naive-ui/lib/tabs/src/Tab'
