export { default as NTable } from 'naive-ui/lib/table/src/Table'
export { default as NTh } from 'naive-ui/lib/table/src/Th'
export { default as NTr } from 'naive-ui/lib/table/src/Tr'
export { default as NTd } from 'naive-ui/lib/table/src/Td'
export { default as NThead } from 'naive-ui/lib/table/src/Thead'
export { default as NTbody } from 'naive-ui/lib/table/src/Tbody'
export type { TableProps } from 'naive-ui/lib/table/src/Table'
